/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Health */
        post: operations["get_health_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "create" | "delete" | "update";
        /** Event */
        Event: {
            /** @description 用户想执行的日程操作 */
            action: components["schemas"]["Action"];
            /**
             * Title
             * @description The title of the event.
             */
            title: string;
            /** @description The start time of the event. */
            start: components["schemas"]["Time"];
            /** @description The end time of the event. */
            end: components["schemas"]["Time"];
            /**
             * Location
             * @description The location of the event.
             */
            location: string | null;
            /**
             * Description
             * @description A description of the event.
             */
            description: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Time */
        Time: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Day */
            day: number;
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
            /**
             * Second
             * @default 0
             */
            second: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_event_post: {
        parameters: {
            query: {
                text: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
